services:
  egservis-db:
    image: mysql:8
    container_name: egservis-db
    volumes:
      - egservis-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=egservis_db
    ports:
      - "3306:3306"
    networks:
      - egservis-network

  egservis-backend:
    build: .
    depends_on:
      - egservis-db
    ports:
      - "3000:3000"
    networks:
      - egservis-network
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - DB_URL=jdbc:mysql://egservis-db:3306/egservis_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - JWT_SECRET=secret
      - PORT=3000
volumes:
  egservis-backend:
  egservis-db:

networks:
  egservis-network:
    driver: bridge
