CREATE TABLE clientes (
    id_cliente BIGINT AUTO_INCREMENT PRIMARY KEY,
    dni VARCHAR(255) UNIQUE NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    num_telefono VARCHAR(255) NOT NULL,
    activo TINYINT(1) NOT NULL DEFAULT 1
);